ignore:
  - "src/core/gpu/**"
  - "src/core/shape.jl"
  - "src/core/abstract_core.jl"
  - "src/core/recurrence.jl"
  - "src/core/measures.jl"
  - "src/core/operation.jl"
  - "src/optimize.jl"
  - "src/utils/gpu_metrics/**"